spring:
  jpa:
    open-in-view: false

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:spring_boot_demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver

logging:
  level:
    ROOT: INFO