CREATE TABLE T_COUNTRY
(
    id   BIGINT auto_increment,
    name VARCHAR(50) NOT NULL
);

INSERT INTO T_COUNTRY (`name`)
VALUES ('Afghanistan'),
       ('Aland Islands'),
       ('Albania'),
       ('Algeria'),
       ('American Samoa'),
       ('Andorra'),
       ('Angola'),
       ('Anguilla'),
       ('Antarctica'),
       ('Antigua And Barbuda'),
       ('Argentina'),
       ('Armenia'),
       ('Aruba'),
       ('Australia'),
       ('Austria'),
       ('Azerbaijan'),
       ('Bahamas'),
       ('Bahrain'),
       ('Bangladesh'),
       ('Barbados'),
       ('Belarus'),
       ('Belgium'),
       ('Belize'),
       ('Benin'),
       ('Bermuda'),
       ('Bhutan'),
       ('Bolivia'),
       ('Bonaire'),
       ('Bosnia And Herzegovina'),
       ('Botswana'),
       ('Brazil'),
       ('British Indian Ocean Territory'),
       ('Brunei Darussalam'),
       ('Bulgaria'),
       ('Burkina Faso'),
       ('Burundi'),
       ('Cambodia'),
       ('Cameroon'),
       ('Canada'),
       ('Cape Verde'),
       ('Cayman Islands'),
       ('Central African Republic'),
       ('Chad'),
       ('Chile'),
       ('China'),
       ('Christmas Island'),
       ('Cocos (Keeling) Islands'),
       ('Colombia'),
       ('Comoros'),
       ('Congo'),
       ('Cook Islands'),
       ('Costa Rica'),
       ('Côte D`Ivoire'),
       ('Croatia'),
       ('Cuba'),
       ('Curaçao'),
       ('Cyprus'),
       ('Czech Republic'),
       ('Denmark'),
       ('Djibouti'),
       ('Dominica'),
       ('Dominican Republic'),
       ('Ecuador'),
       ('Egypt'),
       ('El Salvador'),
       ('Equatorial Guinea'),
       ('Eritrea'),
       ('Estonia'),
       ('Ethiopia'),
       ('Falkland Islands (Malvinas)'),
       ('Faroe Islands'),
       ('Fiji'),
       ('Finland'),
       ('France'),
       ('French Guiana'),
       ('French Polynesia'),
       ('French Southern Territories'),
       ('Gabon'),
       ('Gambia'),
       ('Georgia'),
       ('Germany'),
       ('Ghana'),
       ('Gibraltar'),
       ('Greece'),
       ('Greenland'),
       ('Grenada'),
       ('Guadeloupe'),
       ('Guam'),
       ('Guatemala'),
       ('Guernsey'),
       ('Guinea'),
       ('Guinea-Bissau'),
       ('Guyana'),
       ('Haiti'),
       ('Heard Island And Mcdonald Islands'),
       ('Honduras'),
       ('Hong Kong'),
       ('Hungary'),
       ('Iceland'),
       ('India'),
       ('Indonesia'),
       ('Iran'),
       ('Iraq'),
       ('Ireland'),
       ('Isle Of Man'),
       ('Israel'),
       ('Italy'),
       ('Jamaica'),
       ('Japan'),
       ('Jersey'),
       ('Jordan'),
       ('Kazakhstan'),
       ('Kenya'),
       ('Kiribati'),
       ('Kuwait'),
       ('Kyrgyzstan'),
       ('Laos'),
       ('Latvia'),
       ('Lebanon'),
       ('Lesotho'),
       ('Liberia'),
       ('Libya'),
       ('Liechtenstein'),
       ('Lithuania'),
       ('Luxembourg'),
       ('Macao'),
       ('Madagascar'),
       ('Malawi'),
       ('Malaysia'),
       ('Maldives'),
       ('Mali'),
       ('Malta'),
       ('Marshall Islands'),
       ('Martinique'),
       ('Mauritania'),
       ('Mauritius'),
       ('Mayotte'),
       ('Mexico'),
       ('Micronesia'),
       ('Moldova'),
       ('Mongolia'),
       ('Montenegro'),
       ('Montserrat'),
       ('Morocco'),
       ('Mozambique'),
       ('Myanmar'),
       ('Namibia'),
       ('Nauru'),
       ('Netherlands'),
       ('Netherlands Antilles'),
       ('New Caledonia'),
       ('New Zealand'),
       ('Nicaragua'),
       ('Niger'),
       ('Nigeria'),
       ('North Korea'),
       ('Norway'),
       ('Oman'),
       ('Pakistan'),
       ('Palau'),
       ('Palestine'),
       ('Panama'),
       ('Papua New Guinea'),
       ('Paraguay'),
       ('Peru'),
       ('Philippines'),
       ('Pitcairn'),
       ('Poland'),
       ('Portugal'),
       ('Puerto Rico'),
       ('Qatar'),
       ('Reunion'),
       ('Romania'),
       ('Russian Federation'),
       ('Rwanda'),
       ('Saint Barthelemy'),
       ('Saint Helena, Ascension And Tristan Da Cunha'),
       ('Saint Kitts And Nevis'),
       ('Saint Lucia'),
       ('Saint Pierre And Miquelon'),
       ('Saint Vincent And The Grenadines'),
       ('Samoa'),
       ('San Marino'),
       ('Sao Tome And Principe'),
       ('Saudi Arabia'),
       ('Senegal'),
       ('Serbia'),
       ('Seychelles'),
       ('Sierra Leone'),
       ('Singapore'),
       ('Sint Maarten (Dutch Part)'),
       ('Slovakia'),
       ('Slovenia'),
       ('Solomon Islands'),
       ('Somalia'),
       ('South Africa'),
       ('South Georgia And The South Sandwich Islands'),
       ('South Korea'),
       ('South Sudan'),
       ('Spain'),
       ('Sri Lanka'),
       ('Sudan'),
       ('Suriname'),
       ('Svalbard And Jan Mayen'),
       ('Swaziland'),
       ('Sweden'),
       ('Switzerland'),
       ('Syrian Arab Republic'),
       ('Taiwan'),
       ('Tajikistan'),
       ('Tanzania'),
       ('Thailand'),
       ('Timor-Leste'),
       ('Togo'),
       ('Tokelau'),
       ('Tonga'),
       ('Trinidad And Tobago'),
       ('Tunisia'),
       ('Turkey'),
       ('Turkmenistan'),
       ('Turks And Caicos Islands'),
       ('Tuvalu'),
       ('Uganda'),
       ('Ukraine'),
       ('United Arab Emirates'),
       ('United Kingdom'),
       ('United States'),
       ('United States Minor Outlying Islands'),
       ('Uruguay'),
       ('Uzbekistan'),
       ('Vanuatu'),
       ('Vatican City'),
       ('Venezuela'),
       ('Vietnam'),
       ('Virgin Islands, British'),
       ('Virgin Islands, U.S.'),
       ('Wallis And Futuna'),
       ('Yemen'),
       ('Zambia'),
       ('Zimbabwe');